### ISSUE TITLE
Cannot send message to riemann

### ISSUE THREAD

**Issue by abailly** [tel/riemann-hs#5]
Hello,
I am trying to use this package to send messages to riemann. I modified slightly the client to use TCP instead of UDP, but otherwise left code pretty much untouched. When sending some messages, I can see the messages flow with tcpdump but nothing appears in riemann server. I initially thought this might be some subtle networking issue introduced by the fact I am using docker, but I am able to send messages using another client, e.g. `riemann-cli` in Ruby. 

Not sure what is the state of riemann-hs, if it is supposed to work... I suspect there might be issues with protobuf interface but it appears identical to what's on http://riemann.io. I am clueless.... Help greatly appreciated.

**Comment by tel** [comment]
I'm not actively using or developing this code at the moment. I never really had a use case for TCP either, to be honest, so I'm not at the moment familiar with how to make Riemann work with it.

If you're an active user of this code I could perhaps help you either fix it up and modernize it or replace it with your own, but it would be at the level of exploring the architectural decisions I made in this design more than any specific domain expertise with interop with Riemann.

Sorry about that!

**Comment by abailly** [comment]
Thanks. I am developing an application in Haskell and would really like to feed events to riemann in order to provide an applicative-level performance monitoring, hence my interest in this code. I actually managed to send messages using UDP with a fork from alphaHeavy, but I failed with TCP. I suspect my modifications to use TCP are extremely naive and I should probably go for something more involved, e.g. keeping and using a `Handle` from the socket, managing connection drop, maybe even handle back-pressure from riemann server... Interesting but a bit more involved.

If you dropped usage of that code, can I ask why? I could not find any other implementation of a riemann client in Haskell and this seems puzzling to me as I  think this is a great tool.

**Comment by abailly** [comment]
Reading [Riemann's doc](http://riemann.io/howto.html#write-a-client) I can see that TCP messages should contain a 4-bytes length header... RTFM

**Comment by tel** [comment]
I dropped usage of this code because I simply am not maintaining a service which uses Riemann right now :) 

I'd likely revisit it if I were using Riemann again in the future.

**Comment by abailly** [comment]
I managed to get it working and add a `TCP` constructor so that I can use TCP instead of UDP.

**Comment by tel** [comment]
Glad to hear—if you'd like to create a PR I'd be happy to consider adding it to mainline.

**Comment by abailly** [comment]
Of course !

-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

On Fri, Apr 10, 2015 at 4:30 PM, Joseph Abrahamson <notifications@github.com
