### ISSUE TITLE
Publish riemann-hs to hackage

### ISSUE THREAD

**Issue by abailly** [tel/riemann-hs#8]
This library is not available on hackage which makes it hard to find and use.

**Comment by tel** [comment]
I've been withholding it because it never reached 1.0 while I was using it. If it's already in active use pre-1.0 then I'm happy releasing, though.

Please let me know if you think there are any meaningful blockers on the release. If not then I'll give it some kind of sub 1.0 version number and pop it up.

**Comment by abailly** [comment]
We are using it on a daily basis, even if not with tremendously high loads but at least it does not appear to leak memory nor causes any harm to riemann. It would be great to cut a first release, with whatever number suits you. 0.1 is fine with me if that matters.

**Comment by tel** [comment]
You know, frankly, if it's already in use then I'm not going to pick nits. I'll drum up v0.1.0.0 now.

**Comment by tel** [comment]
0.1.0.0 is available now!

https://hackage.haskell.org/package/riemann

Apparently @telser uploaded it earlier as well. Unsure what's going on there.

**Comment by tel** [comment]
Also let me know and I'll figure out how to give you push access to hackage.

**Comment by telser** [comment]
@tel Way back when I first put it up on hackage, it appeared that no other release was forthcoming (give the age of #5 at the time). So I patched it for our use at work and put it up. Unfortunately with the way hackage works, it looks like my version will still be preferred if you aren't strict with the dep version. This version is better; maybe you could bump the version number above 0.1.0.2 for a hackage release? If you'd rather not do that, the preferred version should probably be set to 0.1 on hackage.

**Comment by tel** [comment]
Ah, gotcha. In that case, I'll go ahead and bump to `0.1.1.0`

**Comment by tel** [comment]
Ah, actually—I can't!

No idea what's going on here but I'm currently locked out of the riemann project. @telser can you add me?

**Comment by telser** [comment]
Sure, what is your username on there? Doesn't seem to be a tel or a jspha on there.

**Comment by tel** [comment]
Nah, mine's from the olden days where you emailed someone with your name and they made up your account name: `JosephAbrahamson`.

**Comment by telser** [comment]
Ah, all done.

**Comment by tel** [comment]
Great!

**Comment by tel** [comment]
Alright! New version `0.1.1.0` is now available on Hackage :)

**Comment by tel** [comment]
Thanks everyone!

**Comment by abailly** [comment]
Thanks a lot. We have other changes pending to better manage queries, could you please give me the rights to push new versions to hackage? My username is abailly.

Thanks

**Comment by tel** [comment]
You’ve been added!
